In [2]:
import numpy as np

In [3]:
file_location = "/data/repos/discrete-opt/coursera-course/knapsack/data/ks_4_0"
t = np.loadtxt(file_location, dtype=int)

In [12]:
t

array([[ 4, 11],
       [ 8,  4],
       [10,  5],
       [15,  8],
       [ 4,  3]])

In [36]:
test = [[0,1,1,0], [1,0,1,0]]
value = t[1:,].transpose()[0:,][0]
weight = t[1:,].transpose()[1:,][0]
option_value = value * test
option_weight = weight * test
option_value.sum(axis=1).argmax()
test[0]


[0, 1, 1, 0]

In [34]:
weight

array([4, 5, 8, 3])

In [39]:
option_weight

array([[0, 5, 8, 0],
       [4, 0, 8, 0]])

In [40]:
option_value

array([[ 0, 10, 15,  0],
       [ 8,  0, 15,  0]])

In [15]:
option
answer = np.where(option_value 

In [10]:
success = '________processed successfully___________ ' 

def do_something_google(href):
    # special code 1
    print('========we do google-specific stuff=======')
    return success + href 

def do_something_bing(href):
    # special code 2
    print('========we do bing-specific stuff=======')
    return success + href 

def do_something_wikipedia(href):
    # special code 3
    print('========we do wikipedia-specific stuff=======')
    return success + href 

In [11]:
l = ['google', 'bing', 'wikipedia']

href = 'https://google.com'

def test(href):
    for e in l:
        if e + '.' in href:
            return globals()['do_something_' + e](href)

test(href)

========we do google-specific stuff=======


'________processed successfully___________ https://google.com'